// Generated by BUCKLESCRIPT VERSION 4.0.5, PLEASE EDIT WITH CARE
'use strict';

var Jest = require("@glennsl/bs-jest/src/jest.js");
var Firebase = require("firebase");
var Js_primitive = require("bs-platform/lib/js/js_primitive.js");
var Setuptest$BsFirebaseX = require("../Setuptest.bs.js");

describe("Firestore", (function () {
        var firebase = Firebase.initializeApp(Setuptest$BsFirebaseX.config);
        describe("Firestore", (function () {
                var firestore = firebase.firestore();
                var options = {
                  timestampsInSnapshots: true
                };
                return Jest.test("should run with errors", (function () {
                              return Jest.Expect[/* toThrow */18](Jest.Expect[/* not_ */23](Jest.Expect[/* expect */0]((function () {
                                                    var arg = Js_primitive.some(options);
                                                    return (function (param) {
                                                                param.settings(arg !== undefined ? Js_primitive.valFromOption(arg) : undefined);
                                                                return /* () */0;
                                                              })(firestore);
                                                  }))));
                            }));
              }));
        return /* () */0;
      }));

/*  Not a pure module */
