// Generated by BUCKLESCRIPT VERSION 4.0.1, PLEASE EDIT WITH CARE
'use strict';

var Firestore = require("firebase/firestore");

var QuerySnapshot = /* module */[];

var DocumentSnapshot = /* module */[];

var DocumentChange = /* module */[];

var DocumentReference = /* module */[];

var CollectionReference = /* module */[];

exports.QuerySnapshot = QuerySnapshot;
exports.DocumentSnapshot = DocumentSnapshot;
exports.DocumentChange = DocumentChange;
exports.DocumentReference = DocumentReference;
exports.CollectionReference = CollectionReference;
/*  Not a pure module */
