// Generated by BUCKLESCRIPT VERSION 4.0.1, PLEASE EDIT WITH CARE
'use strict';


var DocumentSnapshot = /* module */[];

var DocumentReference = /* module */[];

var CollectionReference = /* module */[];

exports.DocumentSnapshot = DocumentSnapshot;
exports.DocumentReference = DocumentReference;
exports.CollectionReference = CollectionReference;
/* No side effect */
