// Generated by BUCKLESCRIPT VERSION 4.0.1, PLEASE EDIT WITH CARE
'use strict';


var DocumentSnapshot = /* module */[];

var DocumentReference = /* module */[];

var CollectionReference = /* module */[];

var Firestore = /* module */[
  /* DocumentSnapshot */DocumentSnapshot,
  /* DocumentReference */DocumentReference,
  /* CollectionReference */CollectionReference
];

exports.Firestore = Firestore;
/* No side effect */
