// Generated by BUCKLESCRIPT VERSION 4.0.1, PLEASE EDIT WITH CARE
'use strict';

var Jest = require("@glennsl/bs-jest/src/jest.js");
var Curry = require("bs-platform/lib/js/curry.js");

describe("Firebase", (function () {
        describe("config", (function () {
                var subject = {
                  projectId: "blah",
                  databaseURL: "halb"
                };
                Jest.test("should generate an object with the correct projectId", (function () {
                        return Curry._2(Jest.Expect[/* Operators */24][/* == */0], Jest.Expect[/* expect */0](subject.projectId), "blah");
                      }));
                return Jest.test("should generate an object with the correct databaseURL", (function () {
                              return Curry._2(Jest.Expect[/* Operators */24][/* == */0], Jest.Expect[/* expect */0](subject.databaseURL), "halb");
                            }));
              }));
        return /* () */0;
      }));

/*  Not a pure module */
